import assert from 'node:assert/strict';
import * as THREE from 'three';
import { createCaveElements } from '../src/planet/cave-elements.js';
const map = new Map();
const storage = { getItem: k => map.get(k) || null, setItem: (k,v) => map.set(k,v) };
const plan = { chambers: Array.from({length: 8}, (_, i) => ({ x: i*50, z: 0, fy: 2, h: 15, rx: 15, rz: 15, kind: 'hall', pools: [] })), field: { cave: (x,y) => y > 17 ? 1 : -4 } };
const create = (extra = {}) => createCaveElements({ plan, group: new THREE.Group(), seed: 42, storage, floor: () => 2, ...extra });
const a = create();
assert.equal(a.stats().sites, 5); assert.equal(a.stats().stones, 15); assert.equal(a.stats().bats, 20);
const first = a.pickables.slice(0,3);
for (const object of first) assert.equal(a.strike({object}),true);
assert.equal(a.stats().completed, 1); assert.equal(map.size,1);
const original = [...map.values()][0];
a.strike({object:first[0]}); assert.equal([...map.values()][0], original);
assert.equal(a.strike({object: new THREE.Mesh()}),false);
const b=create(); assert.equal(b.stats().completed,1); assert.deepEqual(a.pickables.map(o=>o.position.toArray()), b.pickables.map(o=>o.position.toArray()));
for (let t=0; t<100; t+=0.25) a.update(0.25,t);
const lit = a.root.children.find(o=>o.isPointLight); assert.ok(lit.intensity > 0);
for (const mesh of a.root.children.filter(o=>o.isInstancedMesh)) assert.ok([...mesh.instanceMatrix.array].every(Number.isFinite));
const phone=create({isPhone:true}); assert.equal(phone.stats().sites,3); assert.ok(phone.stats().bats<=6);
const lava=create({profile:{caves:{lava:1}}}); assert.equal(lava.stats().bats,0);
const ice=create({profile:{caves:{ice:1}}}); assert.equal(ice.stats().bats,0); assert.equal(ice.pickables[0].userData.material175,'crystal');
const broken=create({storage:{ getItem:()=>'{broken', setItem:()=>assert.fail('must preserve corrupt bytes') }});
for(const object of broken.pickables.slice(0,3)) broken.strike({object});
assert.match(broken.stats().saveError,/preserved/);
const full=create({storage:{getItem:()=>null,setItem:()=>{throw Error('quota');}}});
full.strike({object:full.pickables[0]}); assert.match(full.stats().saveError,/storage/);
// Reduced mobile population must not erase a desktop-only restored alcove.
let crossSave = null;
const crossStorage = {getItem:()=>crossSave,setItem:(_,v)=>{crossSave=v;}};
const desktop = create({storage:crossStorage});
for(const object of desktop.pickables.slice(-3)) desktop.strike({object});
const mobile = create({storage:crossStorage,isPhone:true});
for(const object of mobile.pickables.slice(0,3)) mobile.strike({object});
const revisited = create({storage:crossStorage}); assert.equal(revisited.stats().completed,2);
for(const system of [desktop,mobile,revisited]) system.dispose();
// Same terrain seed and Echo appearance must remain private to each world.
const identityMap = new Map();
const identityStore = {getItem:k=>identityMap.get(k)||null,setItem:(k,v)=>identityMap.set(k,v)};
const terran=create({storage:identityStore,profile:{type:'TERRAN'}});
for(const object of terran.pickables.slice(0,3)) terran.strike({object});
const ocean=create({storage:identityStore,profile:{type:'OCEAN'}}); assert.equal(ocean.stats().completed,0);
const bodyA=create({storage:identityStore,profile:{type:'TERRAN'},bodyKey:'galaxy-A/planet-1'});
for(const object of bodyA.pickables.slice(0,3)) bodyA.strike({object});
const bodyB=create({storage:identityStore,profile:{type:'TERRAN'},bodyKey:'galaxy-B/planet-1'}); assert.equal(bodyB.stats().completed,0);
const returnA=create({storage:identityStore,profile:{type:'TERRAN'},bodyKey:'galaxy-A/planet-1',isPhone:true}); assert.equal(returnA.stats().completed,1);
assert.equal(identityMap.size,2);
for(const system of [terran,ocean,bodyA,bodyB,returnA]) system.dispose();
const camera=new THREE.PerspectiveCamera(); camera.position.set(10000,10000,10000);
const distant=create({camera}); assert.equal(distant.strike({object:distant.pickables[0]}),false);
for(const system of [a,b,phone,lava,ice,broken,full,distant]) {system.dispose(); system.dispose(); assert.equal(system.stats().disposed,true); assert.equal(system.root.parent,null); assert.equal(system.pickables.length,0);}
console.log('Cave elements: bounded pools, stable transforms, planet variants, resonance persistence, corrupt/quota handling, strike distance and disposal passed.');
