// The regional kits: one profile per kind of place, which everything that builds or fills a
// place reads (the settlements, their ground and plants, the air, the people and what they
// wear and do, the sounds, the music's colour and what people talk about). choose.js picks
// one (or blends two) for a point from the atlas region, its culture and its climate; the
// atlas region still gives the particulars (its colours, food, greetings, landmarks).
//
//   build    houses / centre / props: [type, weight] (structures.js builds the types);
//            count [min, max] buildings in a village; layout (layout.js); spread (m); fields
//   ground   paints under a village: path, plaza, yard, field
//   flora    regional plants grown round you (flora.js): [form, weight]
//   air      what hangs in it: snow, dust, mist, haze, pollen; haze tints the fog
//   folk     jobs, errands, roles ([role, weight]: what people are doing), dress (dress.js)
//   sound    beds (sound.js), by day and by night
//   music    a colour on the auto music (never the faceplate itself): pentatonic, phrygian,
//            drone, sparse, swing, register
//   lore     the generated landmarks found here (landmarks.js)
//   travel   how people go on from here, for the talk of the road onward

export const KITS = {
	polar: {
		name: 'Arctic settlement', climate: 'polar',
		build: { houses: [['arctic', 6], ['shed', 2], ['station', 0.6]], centre: ['church-red', 'hall'], props: [['fishrack', 2], ['sledge', 2], ['skiff', 1.5], ['fueltank', 1], ['kayak', 0.6], ['cache', 0.3]], count: [8, 22], layout: 'harbour', spread: 170, fields: null },
		ground: { path: '#c8ccd2', plaza: '#b8bcc2', yard: '#dfe3e8' },
		flora: [['tussock', 3]],
		air: { kind: 'snow', haze: '#c8d4e2', k: 1.25 },
		smoke: 0.35,
		folk: {
			dress: 'arctic', roles: [['walk', 3], ['fish', 2], ['carry', 1.5], ['talk', 2], ['sled', 1]],
			jobs: ['a hunter who fishes through the ice in spring', 'running the co-op store', 'a teacher at the school', 'a carver in soapstone', 'driving the water truck', 'a nurse at the health centre', 'a guide out to the floe edge', 'a mechanic for the snowmobiles', 'a researcher at the station for the season'],
			errands: ['on the way to the co-op', 'checking the nets at the shore', 'going to see the boats', 'bringing tea to an aunt', 'heading out to the land', 'walking home from the school'],
			hobbies: ['throat singing', 'the drum dance', 'fishing for char', 'going out on the land', 'carving', 'hockey in the arena'],
		},
		sound: { day: ['wind', 'ice', 'dogs'], night: ['wind', 'ice'] },
		music: { penta: 1, sparse: 0.4, reg: 4, drone: 0.2 },
		lore: ['shipwreck', 'inuksuk', 'whalers'],
		travel: 'by snowmobile over the sea ice, or by plane when the weather lets it',
	},
	station: {
		name: 'research station', climate: 'polar',
		build: { houses: [['station', 5], ['shed', 2], ['arctic', 1]], centre: ['hall'], props: [['fueltank', 3], ['sledge', 1.5], ['shed', 1]], count: [6, 16], layout: 'harbour', spread: 160, fields: null },
		ground: { path: '#b8bcc2', plaza: '#aeb2b8', yard: '#dfe3e8' },
		flora: [],
		air: { kind: 'snow', haze: '#d2dce8', k: 1.1 },
		smoke: 0.2,
		folk: {
			dress: 'arctic', roles: [['walk', 3], ['carry', 2], ['talk', 2]],
			jobs: ['a glaciologist drilling ice cores', 'the station cook', 'a field guide', 'an electrician keeping the generators going', 'a pilot', 'a penguin biologist', 'the doctor for the season', 'a meteorologist'],
			errands: ['on the way to the mess', 'going to launch the weather balloon', 'heading out to the drill site', 'checking the snow vehicles', 'off to radio home'],
			hobbies: ['the station band', 'cross-country skiing on the flagged route', 'photographing the light', 'the midwinter swim'],
		},
		sound: { day: ['wind', 'ice'], night: ['wind'] },
		music: { lydian: 0.6, sparse: 0.45, reg: 4 },
		lore: ['oldhut', 'shipwreck'],
		travel: 'on the next flight out, when the weather lets it; the ship comes once a summer',
	},
	snow: {
		name: 'snow village', climate: 'boreal',
		build: { houses: [['log', 6], ['shed', 2], ['sauna', 0.8], ['barn', 0.8]], centre: ['church-wood'], props: [['woodpile', 3], ['sledge', 1.5], ['fishrack', 0.8], ['well', 0.6]], count: [10, 28], layout: 'street', spread: 200, fields: 'strip' },
		ground: { path: '#d4d6d8', plaza: '#c8cacc', yard: '#e8eaee', field: '#e2e4e8' },
		flora: [['spruce', 4], ['birch', 2], ['pine', 1.5]],
		air: { kind: 'snow', haze: '#d2dae4', k: 1.15 },
		smoke: 0.9,
		folk: {
			dress: 'boreal', roles: [['walk', 3], ['carry', 2], ['talk', 2], ['chop', 1.5], ['fish', 0.8], ['sled', 1]],
			jobs: ['a forester', 'keeping the village shop', 'driving the school bus', 'a teacher', 'fishing through the lake ice in winter', 'a reindeer herder', 'running the sawmill', 'a nurse at the clinic in town', 'a retired schoolteacher'],
			errands: ['fetching wood for the stove', 'on the way to the shop', 'clearing the path', 'going to check the ice on the lake', 'off to the sauna', 'taking soup to a neighbour'],
			hobbies: ['ice fishing', 'cross-country skiing', 'the sauna', 'berry picking in August', 'hockey', 'knitting'],
		},
		sound: { day: ['wind', 'birdscold', 'chop'], night: ['wind', 'owl'] },
		music: { penta: 0, sparse: 0.25, reg: 2, drone: 0.15 },
		lore: ['oldmine', 'watchtower', 'stonecross'],
		travel: 'down the winter road, or along the frozen river while the ice holds',
	},
	alpine: {
		name: 'alpine village', climate: 'alpine',
		build: { houses: [['chalet', 6], ['haybarn', 2.5], ['shed', 1]], centre: ['chapel'], props: [['woodpile', 2.5], ['trough', 1], ['bench', 1], ['hayrack', 1]], count: [10, 26], layout: 'slope', spread: 220, fields: 'meadow' },
		ground: { path: '#9a9488', plaza: '#a8a298', yard: '#6a8a4a', field: '#7a9a50' },
		flora: [['spruce', 4], ['larch', 2], ['flowers', 1]],
		air: { kind: 'clear', haze: '#c4d4e6', k: 0.8 },
		smoke: 0.6,
		folk: {
			dress: 'alpine', roles: [['walk', 3], ['herd', 1.5], ['talk', 2], ['carry', 1.5], ['sit', 1]],
			jobs: ['a dairy farmer who takes the cows up in summer', 'making cheese at the alp', 'a mountain guide', 'running the guesthouse', 'a ski instructor in winter', 'a carpenter', 'working the cable car', 'a forester'],
			errands: ['on the way down to the dairy', 'walking up to the alp', 'carrying hay to the barn', 'going to the bakery', 'back from mass'],
			hobbies: ['hiking the ridges', 'yodelling in the choir', 'skiing', 'the brass band', 'woodcarving'],
		},
		sound: { day: ['cowbells', 'stream', 'wind'], night: ['stream', 'owl'] },
		music: { penta: 0, sparse: 0.15, reg: 3, lydian: 0.3 },
		lore: ['passshrine', 'watchtower', 'oldmine'],
		travel: 'down the valley road, or over the pass when it is open',
	},
	himalaya: {
		name: 'mountain village', climate: 'highland',
		build: { houses: [['stonehouse', 6], ['shed', 1]], centre: ['gompa', 'chorten'], props: [['chorten', 0.8], ['maniwall', 1], ['flagpole', 2], ['woodpile', 1], ['prayerwheel', 0.8]], count: [8, 22], layout: 'slope', spread: 180, fields: 'terrace' },
		ground: { path: '#9a8a74', plaza: '#a89880', yard: '#8a7a64', field: '#8a9a5a' },
		flora: [['juniper', 2], ['barley', 2], ['pine', 1]],
		air: { kind: 'clear', haze: '#c0d2ea', k: 0.6 },
		smoke: 0.7,
		folk: {
			dress: 'himalaya', roles: [['walk', 3], ['herd', 2], ['carry', 2], ['talk', 2], ['sit', 1], ['monk', 0.6]],
			jobs: ['a yak herder', 'growing barley on the terraces', 'running a teahouse for trekkers', 'a porter on the trail', 'a mountain guide', 'weaving', 'a teacher at the village school', 'a thangka painter'],
			errands: ['carrying water up from the spring', 'taking the yaks to the high pasture', 'walking to the monastery', 'on the way to the teahouse', 'bringing barley to the mill'],
			hobbies: ['archery on festival days', 'singing', 'weaving', 'circling the chorten in the evening'],
		},
		sound: { day: ['wind', 'bells', 'flags'], night: ['wind'] },
		music: { penta: 1, drone: 0.5, sparse: 0.3, reg: 3 },
		lore: ['passshrine', 'watchtower', 'hermitage'],
		travel: 'down the trail to the road head, two days on foot',
	},
	andes: {
		name: 'Andean village', climate: 'highland',
		build: { houses: [['adobethatch', 6], ['shed', 1]], centre: ['chapel-white'], props: [['corral', 2], ['woodpile', 0.6], ['bench', 0.8], ['oven', 1]], count: [8, 22], layout: 'plaza', spread: 180, fields: 'terrace' },
		ground: { path: '#a08a6a', plaza: '#b0a088', yard: '#8a7a5a', field: '#8a9a50' },
		flora: [['ichu', 3], ['eucalyptus', 1], ['quinoa', 1]],
		air: { kind: 'clear', haze: '#c6d4ea', k: 0.65 },
		smoke: 0.6,
		folk: {
			dress: 'andean', roles: [['walk', 3], ['herd', 2], ['stall', 1], ['talk', 2], ['sit', 1], ['weave', 1]],
			jobs: ['herding llamas and alpacas', 'growing potatoes and quinoa', 'weaving at the cooperative', 'selling at the Sunday market', 'driving the colectivo to town', 'a teacher', 'a guide on the old Inca trail'],
			errands: ['taking the llamas up to graze', 'on the way to the market', 'carrying potatoes from the field', 'going to the chapel', 'fetching water'],
			hobbies: ['the panpipes', 'dancing at the fiesta', 'football in the plaza', 'weaving'],
		},
		sound: { day: ['wind', 'bells'], night: ['wind'] },
		music: { penta: 1, sparse: 0.2, reg: 2 },
		lore: ['passshrine', 'incaruin', 'watchtower'],
		travel: 'on the colectivo down the switchbacks to the valley',
	},
	village: {
		name: 'old village', climate: 'temperate',
		build: { houses: [['cottage', 5], ['halftimber', 2], ['barn', 1.5], ['shed', 1]], centre: ['church-stone'], props: [['well', 0.8], ['bench', 1], ['cart', 0.8], ['woodpile', 1], ['wall', 2]], count: [12, 34], layout: 'street', spread: 230, fields: 'strip' },
		ground: { path: '#8a8478', plaza: '#9a9488', yard: '#5a7a3a', field: '#7a8a48' },
		flora: [['oak', 2], ['lime', 2], ['hedge', 2], ['apple', 1]],
		air: { kind: 'haze', haze: '#c4ccd6', k: 1 },
		smoke: 0.4,
		folk: {
			dress: 'village', roles: [['walk', 4], ['talk', 2], ['sit', 1.5], ['carry', 1], ['farm', 1]],
			jobs: ['a farmer', 'keeping the bakery', 'running the pub', 'a vet', 'a teacher at the village school', 'a plumber', 'a retired postman', 'a beekeeper', 'working in town, commuting'],
			errands: ['on the way to the bakery', 'walking the dog round the church', 'going to the market in town', 'back from the allotment', 'off to see the neighbours'],
			hobbies: ['the village football team', 'gardening', 'the choir', 'cycling the lanes', 'baking'],
		},
		sound: { day: ['birds', 'bells'], night: ['owl', 'crickets'] },
		music: { penta: 0, sparse: 0.1 },
		lore: ['stonecircle', 'watchtower', 'stonecross'],
		travel: 'on the bus to the market town, or the train from the next village',
	},
	farm: {
		name: 'farm country', climate: 'temperate',
		build: { houses: [['farmhouse', 4], ['barn', 3], ['silo', 1.5], ['shed', 2]], centre: ['church-steeple', 'store'], props: [['windmill', 0.8], ['fence', 2], ['bales', 1.5], ['truck', 0.8]], count: [6, 16], layout: 'farms', spread: 600, fields: 'strip' },
		ground: { path: '#9a8e78', plaza: '#a49a86', yard: '#6a8a40', field: '#a89a5a' },
		flora: [['oak', 2], ['cottonwood', 2], ['hedge', 1]],
		air: { kind: 'pollen', haze: '#c8d0da', k: 0.9 },
		smoke: 0.15,
		folk: {
			dress: 'farm', roles: [['walk', 3], ['farm', 2], ['talk', 2], ['carry', 1]],
			jobs: ['farming corn and soybeans', 'running cattle', 'at the grain elevator', 'a teacher', 'a mechanic at the co-op', 'driving a truck', 'a vet for large animals'],
			errands: ['heading to the feed store', 'checking the fences', 'on the way to church', 'going into town for parts'],
			hobbies: ['high school football on Friday', 'fishing the creek', 'the county fair', 'hunting in the fall'],
		},
		sound: { day: ['birds', 'wind'], night: ['crickets', 'frogs'] },
		music: { penta: 0.3, swing: 0.05 },
		lore: ['oldbarn', 'watchtower'],
		travel: 'down the county road to the highway',
	},
	outback: {
		name: 'outback station', climate: 'arid',
		build: { houses: [['homestead', 3], ['shed', 3], ['tank', 2]], centre: ['store'], props: [['windmill', 1.5], ['tank', 1.5], ['fence', 1.5], ['truck', 1]], count: [4, 10], layout: 'farms', spread: 400, fields: null },
		ground: { path: '#b86a3a', plaza: '#c07a4a', yard: '#b8804a' },
		flora: [['spinifex', 3], ['gum', 2], ['saltbush', 2]],
		air: { kind: 'dust', haze: '#e0b890', k: 1.1 },
		smoke: 0,
		folk: {
			dress: 'outback', roles: [['walk', 3], ['farm', 1.5], ['talk', 2]],
			jobs: ['running cattle on the station', 'a ringer mustering on a motorbike', 'the station cook', 'flying the mail plane', 'a ranger', 'an artist at the art centre'],
			errands: ['checking the bore', 'on the way to the roadhouse', 'fixing the windmill', 'going out to check the stock'],
			hobbies: ['the races', 'footy', 'painting', 'fishing at the waterhole'],
		},
		sound: { day: ['birdsdry', 'wind', 'insects'], night: ['insects', 'wind'] },
		music: { penta: 0.5, drone: 0.4, swing: 0.05 },
		lore: ['oldbore', 'ruin'],
		travel: 'three hundred k down the road to the next town',
	},
	mediterranean: {
		name: 'Mediterranean village', climate: 'mediterranean',
		build: { houses: [['cube', 4], ['stonetile', 4], ['shed', 0.6]], centre: ['belltower'], props: [['pergola', 1.5], ['bench', 1], ['well', 0.6], ['pots', 2], ['wall', 1.5]], count: [12, 34], layout: 'hill', spread: 200, fields: 'grove' },
		ground: { path: '#c8b898', plaza: '#d8ccb0', yard: '#b8a880', field: '#9a9a6a' },
		flora: [['olive', 4], ['cypress', 2], ['vine', 1], ['citrus', 1]],
		air: { kind: 'haze', haze: '#d8dce4', k: 0.85 },
		smoke: 0.1,
		folk: {
			dress: 'mediterranean', roles: [['walk', 3], ['sit', 2.5], ['talk', 2.5], ['stall', 0.6], ['farm', 1]],
			jobs: ['an olive farmer', 'running the café on the square', 'a fisherman', 'keeping goats', 'a baker', 'a tour guide in summer', 'a retired sailor', 'making cheese'],
			errands: ['on the way to the bakery', 'going down to the harbour', 'taking bread to a neighbour', 'walking to the church', 'out for the evening walk'],
			hobbies: ['backgammon at the café', 'the evening stroll', 'fishing', 'the saint\'s day festival', 'tending the garden'],
		},
		sound: { day: ['cicadas', 'birds', 'bells'], night: ['crickets'] },
		music: { penta: 0, phrygian: 0.4, swing: 0.05 },
		lore: ['watchtower', 'chapelrock', 'ruin'],
		travel: 'on the ferry from the harbour, or the bus along the coast road',
	},
	desert: {
		name: 'desert town', climate: 'desert',
		build: { houses: [['adobe', 6], ['courtyard', 2], ['shed', 0.6]], centre: ['well', 'mosque-small'], props: [['shade', 2], ['palmgrove', 1], ['jars', 1.5], ['wall', 1.5], ['oven', 0.8]], count: [10, 30], layout: 'compact', spread: 160, fields: 'oasis' },
		ground: { path: '#c8a878', plaza: '#d4b688', yard: '#c09868', field: '#7a8a4a' },
		flora: [['datepalm', 4], ['acacia', 2], ['tamarisk', 1]],
		air: { kind: 'dust', haze: '#e4c8a0', k: 1.2 },
		smoke: 0.2,
		folk: {
			dress: 'desert', roles: [['walk', 3], ['sit', 2], ['talk', 2], ['herd', 1], ['farm', 1], ['tea', 1]],
			jobs: ['tending the date palms', 'a camel herder', 'keeping goats', 'a driver on the desert road', 'running the shop', 'a teacher', 'a well-digger', 'a guide for travellers'],
			errands: ['going to the well', 'on the way to the gardens before the heat', 'taking the goats out', 'going to the market', 'bringing tea'],
			hobbies: ['tea in the evening', 'poetry', 'music on the tinde drum', 'telling stories at night'],
		},
		sound: { day: ['wind', 'goats'], night: ['wind', 'insects'] },
		music: { phrygian: 1, drone: 0.6, sparse: 0.2 },
		lore: ['caravanserai', 'ruin', 'oldwell'],
		travel: 'with the trucks on the desert road, or the old caravan way between the wells',
	},
	pueblo: {
		name: 'adobe village', climate: 'desert',
		build: { houses: [['pueblo', 5], ['adobe', 3], ['shed', 1]], centre: ['mission'], props: [['ladder', 1.5], ['oven', 1.5], ['ristra', 1], ['wall', 1]], count: [8, 24], layout: 'plaza', spread: 160, fields: 'strip' },
		ground: { path: '#c49a70', plaza: '#cca880', yard: '#b8906a', field: '#8a8a50' },
		flora: [['juniper', 2], ['cottonwood', 1], ['sagebrush', 3], ['cactus', 1]],
		air: { kind: 'dust', haze: '#dcc8b0', k: 0.9 },
		smoke: 0.4,
		folk: {
			dress: 'farm', roles: [['walk', 3], ['sit', 2], ['talk', 2], ['stall', 1]],
			jobs: ['a potter', 'a silversmith', 'farming chile', 'a teacher', 'a ranger', 'baking in the hornos', 'working at the tribal office'],
			errands: ['on the way to the plaza', 'baking bread in the horno', 'going to the feast day', 'bringing chile in'],
			hobbies: ['pottery', 'the feast day dances', 'basketball', 'hunting in the fall'],
		},
		sound: { day: ['wind', 'birdsdry'], night: ['wind', 'crickets'] },
		music: { penta: 0.6, drone: 0.3 },
		lore: ['ruin', 'watchtower'],
		travel: 'down the highway to the city',
	},
	bazaar: {
		name: 'old town and bazaar', climate: 'dry',
		build: { houses: [['townhouse', 5], ['courtyard', 3]], centre: ['mosque', 'teahouse'], props: [['fountain', 0.6], ['shade', 1.5], ['jars', 1], ['bench', 1]], count: [40, 120], layout: 'souk', spread: 320, fields: null, dense: true },
		ground: { path: '#c8b090', plaza: '#d4c0a0', yard: '#bca484' },
		flora: [['datepalm', 2], ['citrus', 2], ['planetree', 1]],
		air: { kind: 'dust', haze: '#e0d0b4', k: 1.05 },
		smoke: 0.15,
		folk: {
			dress: 'bazaar', roles: [['stall', 4], ['walk', 4], ['tea', 1.5], ['talk', 2], ['sit', 1.5], ['carry', 1]],
			jobs: ['a spice merchant', 'selling carpets', 'a coppersmith', 'running a tea house', 'selling fabric', 'a baker', 'a tailor', 'a shoemaker', 'a calligrapher', 'selling fruit and vegetables', 'a schoolteacher'],
			errands: ['on the way to the bazaar', 'taking tea to a stallholder', 'buying bread', 'going to the mosque', 'carrying bolts of cloth to the tailor'],
			hobbies: ['backgammon at the tea house', 'football', 'poetry', 'the oud', 'calligraphy'],
		},
		sound: { day: ['market', 'clinks', 'birds'], night: ['crickets', 'wind'] },
		music: { phrygian: 1, drone: 0.4, swing: 0.08 },
		lore: ['caravanserai', 'watchtower', 'oldwell'],
		travel: 'with the shared taxis from the square, or the old caravan road',
	},
	steppe: {
		name: 'herders\' camp', climate: 'steppe',
		build: { houses: [['ger', 6], ['shed', 0.5]], centre: ['ger-large'], props: [['pen', 1.5], ['hitch', 2], ['solar', 1], ['cart', 0.5], ['ovoo', 0.3]], count: [3, 9], layout: 'camp', spread: 120, fields: null },
		ground: { path: '#9a9a6a', plaza: '#a8a478', yard: '#8a9a5a' },
		flora: [['steppegrass', 4], ['feathergrass', 2]],
		air: { kind: 'clear', haze: '#c8d6e8', k: 0.6 },
		smoke: 0.8,
		folk: {
			dress: 'steppe', roles: [['herd', 3], ['walk', 2], ['talk', 2], ['sit', 1.5], ['carry', 1]],
			jobs: ['a herder of horses, sheep and goats', 'milking the mares for airag', 'a wrestler training for Naadam', 'making felt', 'a vet who rides between camps', 'a teacher at the sum centre school', 'driving a jeep between the camps'],
			errands: ['bringing the horses in', 'fetching water from the well', 'going to the next camp to visit', 'checking the sheep', 'riding to the sum centre'],
			hobbies: ['horse racing', 'wrestling', 'archery', 'the morin khuur', 'long song'],
		},
		sound: { day: ['wind', 'horses', 'sheep'], night: ['wind'] },
		music: { penta: 1, drone: 0.7, sparse: 0.3 },
		lore: ['ovoo', 'deerstone', 'caravanserai'],
		travel: 'across the grass by motorbike or horse; the jeep tracks run on to the sum centre',
	},
	savanna: {
		name: 'savanna village', climate: 'savanna',
		build: { houses: [['rondavel', 5], ['tinroof', 3], ['granary', 1.5]], centre: ['church-small', 'school'], props: [['kraal', 1.5], ['bench', 1], ['jars', 1], ['fireplace', 1], ['bicycle', 0.6]], count: [8, 24], layout: 'kraal', spread: 200, fields: 'plots' },
		ground: { path: '#b07a4a', plaza: '#b8845a', yard: '#a8744a', field: '#8a7a3a' },
		flora: [['acacia', 4], ['baobab', 0.6], ['savannagrass', 3], ['euphorbia', 0.6]],
		air: { kind: 'dust', haze: '#e4cfa8', k: 1 },
		smoke: 0.5,
		folk: {
			dress: 'savanna', roles: [['walk', 3], ['herd', 2], ['carry', 2], ['talk', 2], ['sit', 1.5], ['farm', 1]],
			jobs: ['herding cattle', 'growing maize and beans', 'a teacher at the primary school', 'a community health worker', 'a ranger at the conservancy', 'a beadworker', 'running a small shop', 'a boda-boda rider'],
			errands: ['carrying water from the borehole', 'taking the cattle out', 'on the way to the market', 'going to church', 'walking to the school'],
			hobbies: ['football', 'singing in the choir', 'beadwork', 'running'],
		},
		sound: { day: ['birdsdry', 'cattle', 'insects'], night: ['insects', 'frogs', 'nightbirds'] },
		music: { penta: 0.6, swing: 0.1 },
		lore: ['baobab', 'ruin', 'oldwell'],
		travel: 'on a matatu from the junction, or a boda-boda if you are in a hurry',
	},
	sahel: {
		name: 'Sahel village', climate: 'savanna',
		build: { houses: [['mudhouse', 5], ['granary', 3], ['rondavel', 1]], centre: ['mudmosque', 'well'], props: [['kraal', 1], ['jars', 1.5], ['shade', 1.5], ['fireplace', 1]], count: [10, 30], layout: 'compact', spread: 180, fields: 'plots' },
		ground: { path: '#c8986a', plaza: '#d0a476', yard: '#be905e', field: '#a08a4a' },
		flora: [['acacia', 3], ['neem', 2], ['baobab', 1], ['savannagrass', 2]],
		air: { kind: 'dust', haze: '#e6c49a', k: 1.25 },
		smoke: 0.5,
		folk: {
			dress: 'sahel', roles: [['walk', 3], ['herd', 2], ['carry', 2], ['talk', 2], ['sit', 2], ['tea', 1]],
			jobs: ['growing millet and sorghum', 'herding cattle with the seasons', 'a mason who replasters the mosque', 'a griot who keeps the old songs', 'selling at the weekly market', 'a teacher', 'a well-digger'],
			errands: ['drawing water at the well', 'pounding millet', 'going to the weekly market', 'taking the cattle to water', 'on the way to prayer'],
			hobbies: ['the kora', 'football', 'tea in three rounds', 'storytelling'],
		},
		sound: { day: ['wind', 'birdsdry', 'goats'], night: ['insects', 'wind'] },
		music: { penta: 0.8, drone: 0.4, swing: 0.1 },
		lore: ['oldwell', 'ruin', 'baobab'],
		travel: 'by bush taxi along the laterite road, or a pirogue on the river',
	},
	jungle: {
		name: 'rainforest village', climate: 'rainforest',
		build: { houses: [['stilt', 5], ['hut', 2.5], ['tarp', 2.5], ['longhouse', 0.4]], centre: ['longhouse', 'church-small'], props: [['canoe', 1.5], ['garden', 1.5], ['line', 1.5], ['fireplace', 1], ['hammock', 1]], count: [8, 24], layout: 'river', spread: 170, fields: 'plots' },
		ground: { path: '#6a4a2a', plaza: '#7a5a38', yard: '#5a4a2a', field: '#4a5a28' },
		flora: [['emergent', 2], ['banana', 3], ['fern', 3], ['palm', 2], ['bamboo', 1], ['liana', 1]],
		air: { kind: 'mist', haze: '#b8c8b8', k: 1.5 },
		smoke: 0.4,
		folk: {
			dress: 'tropical', roles: [['walk', 3], ['carry', 2], ['fish', 1.5], ['talk', 2], ['sit', 2], ['farm', 1]],
			jobs: ['fishing the river', 'tending the garden plots', 'a boat driver', 'a teacher at the village school', 'gathering forest fruits and medicines', 'a ranger with the forest patrol', 'weaving baskets and mats', 'a carpenter who builds the stilt houses'],
			errands: ['going down to the river', 'carrying cassava back from the garden', 'on the way to the school', 'checking the fish traps', 'taking the canoe across'],
			hobbies: ['football on the strip by the river', 'singing', 'weaving', 'fishing at dusk'],
		},
		sound: { day: ['insectsjungle', 'birdsjungle', 'river'], night: ['frogs', 'insectsnight', 'nightbirds'] },
		music: { penta: 0.6, arp: 0.3, swing: 0.1 },
		lore: ['sacredtree', 'ruin', 'oldbridge'],
		travel: 'downriver by boat, a day to the town with the road',
	},
	island: {
		name: 'island village', climate: 'tropical',
		build: { houses: [['fale', 4], ['tincottage', 4], ['hut', 1]], centre: ['church-white'], props: [['outrigger', 2], ['line', 1], ['fireplace', 1], ['bench', 1]], count: [8, 26], layout: 'shore', spread: 220, fields: 'plots' },
		ground: { path: '#d8c8a0', plaza: '#e0d4b4', yard: '#7a9a4a', field: '#5a7a38' },
		flora: [['coconut', 5], ['breadfruit', 1.5], ['banana', 1.5], ['hibiscus', 1]],
		air: { kind: 'haze', haze: '#d4e2ea', k: 0.9 },
		smoke: 0.3,
		folk: {
			dress: 'island', roles: [['walk', 3], ['sit', 2.5], ['fish', 1.5], ['talk', 2], ['carry', 1]],
			jobs: ['a fisherman', 'growing taro and breadfruit', 'a teacher at the church school', 'running the small store', 'a boat builder', 'a nurse at the dispensary', 'weaving mats from pandanus'],
			errands: ['going down to the lagoon', 'on the way to church', 'taking fish to the family', 'walking to the store'],
			hobbies: ['rugby', 'singing in the church choir', 'fishing at night', 'dancing'],
		},
		sound: { day: ['surf', 'birds', 'wind'], night: ['surf', 'insectsnight'] },
		music: { penta: 0.5, swing: 0.15 },
		lore: ['shipwreck', 'sacredtree', 'lighthouse'],
		travel: 'on the inter-island boat on Tuesday, weather permitting',
	},
	eastvillage: {
		name: 'East Asian village', climate: 'monsoon',
		build: { houses: [['easthouse', 6], ['shed', 1]], centre: ['templehall', 'pagoda'], props: [['lanternpost', 1.5], ['stonelantern', 0.8], ['woodpile', 0.6], ['bench', 1], ['torii', 0.4]], count: [12, 36], layout: 'lanes', spread: 220, fields: 'paddy' },
		ground: { path: '#8a8478', plaza: '#9a968c', yard: '#7a7a68', field: '#5a8a48' },
		flora: [['bamboo', 3], ['pine', 1.5], ['blossom', 2], ['maple', 1], ['tea', 1]],
		air: { kind: 'mist', haze: '#c8d4dc', k: 1.1 },
		smoke: 0.4,
		folk: {
			dress: 'eastasia', roles: [['walk', 3], ['farm', 2], ['sit', 2], ['talk', 2], ['stall', 1], ['carry', 1]],
			jobs: ['growing rice on the terraces', 'picking tea', 'running the noodle shop', 'a teacher', 'a woodworker', 'keeping the temple', 'making tofu', 'a retired farmer who still keeps a plot'],
			errands: ['going to check the paddies', 'on the way to the market', 'bringing vegetables to the shop', 'walking to the temple', 'taking the grandchildren to school'],
			hobbies: ['tai chi in the morning', 'calligraphy', 'xiangqi in the square', 'growing vegetables', 'singing'],
		},
		sound: { day: ['birds', 'stream', 'templebell'], night: ['frogs', 'insectsnight'] },
		music: { penta: 1, sparse: 0.2, reg: 1 },
		lore: ['passshrine', 'oldbridge', 'watchtower'],
		travel: 'on the bus from the crossroads to the county town',
	},
	eastcity: {
		name: 'East Asian city', climate: 'monsoon',
		build: { houses: [['neonblock', 4], ['shophouse', 5]], centre: ['templehall', 'pagoda'], props: [['lanternstring', 2], ['stall', 2], ['bikes', 1.5], ['vending', 1]], count: [60, 160], layout: 'blocks', spread: 360, fields: null, dense: true },
		ground: { path: '#6a6a6a', plaza: '#7a7a78', yard: '#6a6a66' },
		flora: [['planetree', 2], ['blossom', 1], ['bamboo', 1]],
		air: { kind: 'haze', haze: '#c8ccd4', k: 1.15 },
		smoke: 0.25,
		folk: {
			dress: 'city', roles: [['walk', 5], ['stall', 2], ['talk', 2], ['sit', 1.5]],
			jobs: ['an office worker', 'running a noodle stall', 'a delivery rider', 'a nurse', 'a student', 'a programmer', 'a shopkeeper', 'a taxi driver', 'a chef', 'a barista'],
			errands: ['on the way to the station', 'getting dinner at the stalls', 'going back to the office', 'meeting friends', 'picking up a parcel'],
			hobbies: ['karaoke', 'basketball', 'photography', 'gaming', 'hiking on the weekend'],
		},
		sound: { day: ['citybed', 'market'], night: ['citybed', 'market'] },
		music: { penta: 0.8, swing: 0.05 },
		lore: ['oldbridge', 'watchtower'],
		travel: 'on the metro, or the fast train from the main station',
	},
	southcity: {
		name: 'South Asian city', climate: 'monsoon',
		build: { houses: [['flatbrick', 4], ['shophouse', 5]], centre: ['mandir', 'chai'], props: [['stall', 2], ['chai', 1], ['cart', 1]], count: [60, 160], layout: 'blocks', spread: 340, fields: null, dense: true },
		ground: { path: '#8a8070', plaza: '#a09484', yard: '#8a7e6e' },
		flora: [['neem', 2], ['palm', 1], ['banyan', 0.5]],
		air: { kind: 'haze', haze: '#d8ccb8', k: 1.35 },
		smoke: 0.3,
		folk: {
			dress: 'southasia', roles: [['walk', 5], ['stall', 2.5], ['tea', 1.5], ['talk', 2], ['sit', 1.5]],
			jobs: ['running a sweet shop', 'an auto-rickshaw driver', 'a software engineer', 'a tailor in the market', 'a pharmacist', 'a schoolteacher', 'selling vegetables from a cart', 'a doctor at the clinic', 'a student'],
			errands: ['on the way to the market', 'catching the bus', 'getting chai between errands', 'going to the temple', 'picking up the children'],
			hobbies: ['cricket', 'films', 'cooking', 'music', 'badminton'],
		},
		sound: { day: ['citybed', 'market', 'bells'], night: ['citybed', 'insectsnight'] },
		music: { drone: 0.6, phrygian: 0.3, swing: 0.05 },
		lore: ['stepwell', 'ruin'],
		travel: 'on the train from the junction, or a night bus',
	},
	southasia: {
		name: 'South Asian village', climate: 'monsoon',
		build: { houses: [['flatbrick', 5], ['mudtile', 3], ['shed', 0.6]], centre: ['mandir', 'banyan'], props: [['chai', 1.2], ['handpump', 1], ['haystack', 1.2], ['charpai', 1.2], ['cart', 0.6]], count: [14, 40], layout: 'compact', spread: 200, fields: 'strip' },
		ground: { path: '#b09070', plaza: '#bca080', yard: '#a88a68', field: '#6a8a3a' },
		flora: [['neem', 2], ['banyan', 0.6], ['mango', 2], ['palm', 1], ['sugarcane', 1]],
		air: { kind: 'haze', haze: '#dcd0bc', k: 1.25 },
		smoke: 0.5,
		folk: {
			dress: 'southasia', roles: [['walk', 3], ['sit', 2.5], ['talk', 2.5], ['farm', 1.5], ['tea', 1.2], ['stall', 1], ['carry', 1]],
			jobs: ['growing wheat and rice', 'running the chai stall', 'a schoolteacher', 'an auto-rickshaw driver', 'tailoring', 'keeping buffaloes for milk', 'a priest at the temple', 'a pharmacist in the bazaar', 'studying engineering'],
			errands: ['on the way to the market', 'taking milk to the dairy', 'walking to the temple', 'going to the fields early before the heat', 'picking up the children from school'],
			hobbies: ['cricket', 'kabaddi', 'devotional songs', 'cooking for festivals', 'films'],
		},
		sound: { day: ['birds', 'market', 'bells'], night: ['insectsnight', 'frogs'] },
		music: { drone: 0.7, phrygian: 0.3, swing: 0.05 },
		lore: ['sacredtree', 'stepwell', 'ruin'],
		travel: 'on the bus from the chowk, or the train from the district town',
	},
};

// the kits as a list (stable order)
export const KIT_IDS = Object.keys(KITS);
for (const id of KIT_IDS) KITS[id].id = id;
