// Match the dining chairs generated by bay/housekit.js. Their centres are measured in
// the house's local frame; occupants use the existing furniture rather than adding a
// second table and chairs on top of it.
export function diningSeats(item) {
	const n = item.chairs || 4, per = Math.ceil(n / 2), angle = (item.rot || 0) * Math.PI / 2;
	const out = [];
	for (let row = 0; row < per; row++) for (const side of [1, -1]) {
		if (side < 0 && row >= n - per) continue;
		const x = -item.w / 2 + item.w * (row + .5) / per, z = side * (item.d / 2 + .12);
		out.push({ x: item.x + x * Math.cos(angle) + z * Math.sin(angle), z: item.z - x * Math.sin(angle) + z * Math.cos(angle), y: item.y, heading: angle + (side > 0 ? Math.PI : 0) });
	}
	return out;
}
